### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by CyanMY**

### CODE REVIEW

**Comment by Justw8** [comment]
Heya, thanks for your translations, but the support for localization is done through curseforge: 
https://www.curseforge.com/wow/addons/nameplate-scrolling-combat-text/localization

**Comment by CyanMY** [comment]
> Heya, thanks for your translations, but the support for localization is done through curseforge:
> https://www.curseforge.com/wow/addons/nameplate-scrolling-combat-text/localization

OK.

**Comment by Justw8** [comment]
https://www.curseforge.com/wow/addons/nameplate-scrolling-combat-text/localization/languages/99/phrases#304191

Here is the page for Simplified Chinese!

**Comment by CyanMY** [comment]
> https://www.curseforge.com/wow/addons/nameplate-scrolling-combat-text/localization/languages/99/phrases#304191
> 
> Here is the page for Simplified Chinese!

Thanks.
I will try to do it.

**Comment by Justw8** [comment]
I have approved the translations and tagged so it gets added to the addon.

**Pull request closed without merging**
