### PR TITLE
Update NameplateSCT.lua

### PR DESCRIPTION
**Pull request by 1ps3**
Add font flat options and text shadow toggle
wow_2018-09-12_19-34-35

### CODE REVIEW

**Comment by Justw8** [comment]
Heya, this repo is not representative of the current Nameplate code, but I will take a look once I am done with progress raiding sometime in the next few weeks to merge this. Thanks!

**Comment by 1ps3** [comment]
Yea, I figured after I made a PR. All good enjoy prog and GL for WF.

**Comment by Justw8** [comment]
Just as an update, looking at it this upcoming weekend :)

**Comment by Justw8** [comment]
Sorry it took a while, this will be in 1.15 on curse/twitch soon :)

**Comment by 1ps3** [comment]
All good, I'd stay away from the game after prog too. :)

**Pull request closed without merging**
