### PR TITLE
Seperate icon from the fontString

### PR DESCRIPTION
**Pull request by 1ps3**
Since I don't really know where to put these I'm just going to make another PR. 
This PR simply removes the icon front the text and allows the user to position it how ever they would like around the fontString. This also means that other addons can skin the icon how ever they like, I've addon masque support to NSCT in this PR too but there's still some bugs and stuff that I literally have no idea how to fix, one of them being that the masque skinning is on a different layer to the icon textue and I couldn't really figure that out at all since I noticed you were settings some layer stuff. Also I don't know why when an icon is created for the first time and added to the pool it doesn't anchor to the fontString properly.

### CODE REVIEW

**Comment by 1ps3** [comment]
https://gfycat.com/jointwatchfulgalago

**Comment by 1ps3** [comment]
Fixed up the PR and everything seems fine, just can't figure out the layering issue. I did somehow manage to make it happen less, but it's probably just random chance with pooling.

**Comment by Justw8** [comment]
Heya, I will take a look sometime after Crucible is done :)

**Comment by 1ps3** [comment]
Yea I always end up making these when you're in the middle of prog. Boss is such a pain, it's pretty sick though too GL and get that WF.

**Comment by Justw8** [comment]
I will merge/add this when the 8.2 changes are tested a bit more and working okay. Had to remove some animation stuff :(

**Comment by 1ps3** [comment]
Yea I saw, idk why they're doing this shit. It's so fucking annoying.

**Comment by Justw8** [comment]
Going to look at this after the weekend to see and get it in before shadowlands. :) if you are still here; feel free to resolve any conflicts right now.

**Comment by 1ps3** [comment]
Ah I forgot I made this pr. I'll take a look I suppose. There's something that I wanted to fix with it that I never got around to. Idk how to see conflicted on git. So I'll just use the latest version on live and see where that gets me.

**Comment by Justw8** [comment]
Usually it allows you to see the conflict(s), but it says it's too complex to show ^^ :p

**Comment by Justw8** [comment]
I worked my way through it and got as far as what I just pushed to your fork. Was the weird thing you saw happening in the past the icons disapearing and being weird? because it does not work fully yet.

**Comment by 1ps3** [comment]
Something like that yea, when there's no spell texture, I think I was still setting the border. I can't remember if I fixed that or not, but there was another issue with layers/strata. I wasn't sure what was causing it but it seemed like the spell textures and masque skins weren't on the same layer.

**Comment by Justw8** [comment]
https://streamable.com/pdtx2a

This is where I'm at right now. the skin's arn't always applied from the start :(

**Comment by 1ps3** [comment]
I see, I can take a look in a few hours, see where I get with it if you want to post what you have.

**Comment by Justw8** [comment]
fixed the conflicts up by merging from the master here. Now we just have to fix the bug(s).

**Comment by Justw8** [comment]
> I see, I can take a look in a few hours, see where I get with it if you want to post what you have.

The repo is uptodate with what I used from your code before, I did get rid of the icon recycling, although that might be needed to be added back eventually.

**Comment by Justw8** [comment]
Fixed the issue of when things are skinned, only the draw layer problem is left now.

see: https://streamable.com/g8me8o

**Comment by 1ps3** [comment]
I found a few issues in the most recent version (I think). Should check if masque is enabled before trying to actually call the reskin function. Also should check if icon in the recycle function, because with white hits it doesn't, and those spells that don't have icons. There was also an issue that I can't remember if I PR'd. NSCT was erroring out when the spell didn't have a texture. I noticed this while doing the Infuriating the Emperor quest in vul'dun

**Comment by 1ps3** [comment]
I think the only way to get around the layering issue is to create a frame for each of the fontstrings. Since the only frame atm is the NSCT frame, all the textures are on that frame. I think that's the issue.

**Comment by Justw8** [comment]
> I found a few issues in the most recent version (I think). Should check if masque is enabled before trying to actually call the reskin function. Also should check if icon in the recycle function, because with white hits it doesn't, and those spells that don't have icons. There was also an issue that I can't remember if I PR'd. NSCT was erroring out when the spell didn't have a texture. I noticed this while doing the Infuriating the Emperor quest in vul'dun

yea, these are little things that I didn't want to worry about yet while trying to get it all working with masque on in the first place.

> I think the only way to get around the layering issue is to create a frame for each of the fontstrings. Since the only frame atm is the NSCT frame, all the textures are on that frame. I think that's the issue.

after trying some more last night, I think so as well. That's quite the refactor though

**Comment by 1ps3** [comment]
Okay, so I was working on changing each damage event to frames and it seems to be working out fine atm. I'm just working with fontstrings at the moment, going to start getting icons in there now.

**Comment by Justw8** [comment]
I also got as far as having it nearly working properly now, and working on refinement. perhaps you have discord so we can talk more directly? :)

**Pull request merged**
